// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mainContainer': string;
  'outerContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
